apiVersion: v1
kind: Service
metadata:
  name: server-svc
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 1234
      targetPort: 3003